feat: show an input box to get identifier
Health-RI/health-ri-metadata pull request #105
Opened 2024-06-24 12:06 UTC by xiaofengleo

In AgentShape, the Identifier is mandatory. The publisher is of type AgentShape, it is required to input an ID for the publisher. A box should be displayed for a user to input the ID, that requeirs the dash:viewer dash:LiteralViewer ;  dash:editor dash:TextFieldEditor ; for the identifier.

2024-06-24 12:16 UTC, kburger requested changes

2024-06-24 12:16 UTC, kburger commented on Formalisation(shacl)/Core/PiecesShape/Dataset.ttl
> +sh:targetClass foaf:Agent .
Missing newline at EOF.

2024-06-24 12:16 UTC, kburger commented on Formalisation(shacl)/Core/PiecesShape/Catalog.ttl
Very inconsistent use of tabs/spaces for indentation.

2024-06-25 09:05 UTC, xiaofengleo commented on Formalisation(shacl)/Core/PiecesShape/Catalog.ttl
done

2024-06-25 09:34 UTC, kburger approved these changes
Looks good enough to me.

2024-06-25 09:37 UTC, merged