feat: pulisher sh:node :AgentShape ->sh:class foaf:Agent
Health-RI/health-ri-metadata pull request #107
Opened 2024-07-01 21:04 UTC by xiaofengleo

pulisher sh:node :AgentShape ->sh:class foaf:Agent ;
addressing github issue 101 https://github.com/Health-RI/health-ri-metadata/issues/101

2024-07-02 11:15 UTC, kburger requested changes

2024-07-02 11:15 UTC, kburger commented on Formalisation(shacl)/Core/PiecesShape/DataService.ttl
This file does not belong in this pull request. Please remove.

2024-07-02 11:15 UTC, kburger commented on Formalisation(shacl)/Core/PiecesShape/DatasetSeries.ttl
> +    #sh:node :AgentShape ;
What is the intent here? This requires an IRI to be entered by the user, but will not allow them to fill in the nested fields. What do we want the user to enter?

2024-07-02 21:41 UTC, xiaofengleo commented on Formalisation(shacl)/Core/PiecesShape/DataService.ttl
removed.

2024-07-08 08:19 UTC, kburger commented
I don't see any changes since last time this issue was discussed. The conclusion then was to align with the solution from `dcat:Dataset`, as seen at https://github.com/Health-RI/health-ri-metadata/blob/develop/Formalisation(shacl)/Core/PiecesShape/Dataset.ttl#L85-L90.

2024-07-08 11:44 UTC, kburger approved these changes
LGTM, but did not test it on an FDP yet.

2024-07-08 11:48 UTC, merged